--Create View named 'BrandFinance'
CREATE VIEW BrandFinance
AS
(
SELECT
		rf.[product_id]
		,rb.brand
      ,rf.[listing_price]
      ,rf.[sale_price]
      ,rf.[discount]
      ,rf.[revenue]
	  ,rr.rating
	  ,rr.reviews
  FROM [OnlineSportRetail].[retail].[Finance] AS rf
  LEFT JOIN [OnlineSportRetail].[retail].[Brand] AS rb
  ON rf.product_id = rb.product_id
  LEFT JOIN [OnlineSportRetail].retail.Reviews AS rr
    ON rr.product_id = rf.product_id
  WHERE rb.brand IS NOT NULL
  )
  
  --QUESTION 1
--How do the price points of Nike and Adidas products differ?
  SELECT brand 
  ,SUM(sale_price) AS TotalSalesPrice
   ,MIN(sale_price) AS MinimumSalesPrice
   ,MAX(sale_price) AS MaximumSalesPrice
      ,AVG(sale_price) AS AverageSalesPrice
   ,COUNT(product_id) AS ProductCount
  FROM BrandFinance
  GROUP BY brand
  




  --Question 2 
  --Is there a difference in the amount of discount offered between the brands?
   SELECT
   brand
   ,SUM(discount) AS TotalDiscountOnProduct
    ,ROUND(AVG(discount),2) AS AverageDiscountOnProduct
   FROM BrandFinance
   GROUP BY brand

   --Answer: Adidas has an average discount of 0.33 and Nike has on discount on any of their products



   --Question 3
   --Are there any trends or gaps in the volume of reviews by month?
   WITH DateMonthCTE 
   AS
   (
   SELECT 
   bf.reviews
   ,DATENAME(MONTH, rt.last_visited) AS DateMonth
   FROM BrandFinance bf
   LEFT JOIN retail.Traffic rt
   ON bf.product_id = rt.product_id
   WHERE last_visited IS NOT NULL
)
SELECT SUM(reviews) AS TotalReviews
, DateMonth 
FROM DateMonthCTE
GROUP BY DateMonth

 
 
   --Question 4
   --How much of the company's stock consists of footwear items? 
   --What is the median revenue generated by these products?

   SELECT * FROM BrandFinance

   WITH OrderedData AS (
    SELECT revenue,
           ROW_NUMBER() OVER (ORDER BY revenue) AS RowNumber,
           COUNT(*) OVER () AS TotalRows
    FROM BrandFinance
	WHERE revenue > 0
)
SELECT AVG(revenue) AS MedianRevenue
FROM OrderedData
WHERE RowNumber IN ((TotalRows + 1) / 2, (TotalRows + 2) / 2);
 

 
